name: 'JMeter Plugin Publish'
description: 'Automatically publish JMeter Plugin into JMeter Plugins Manager repository'
author: 'Abstracta'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  upstream-repository:
    description: 'Url of target jmeter-plugins repository'
    required: false
    default: 'https://github.com/undera/jmeter-plugins.git'
  forked-repository:
    description: 'Your forked repository of undera/jmeter-plugins used to send PR from'
    required: true
  plugin-artifact-name:
    description:
      'Prefix of the plugin artifact name used to identify the jar from other libs placed in github
      release'
    required: true
  plugin-id:
    description: 'Registered ID for identifing the plugin in jmeter-plugins'
    required: true
  token:
    description: 'Github token (PAT) used to fetch assets from latest release and open the PR'
    required: true
  changes:
    description: 'Release note line'
    required: true
  ignore-dependencies:
    description:
      "Prefix of dependencies separated by commas, which won't be taken into consideration at
      jmeter-plugins release but are present in github release"
    required: false

outputs:
  pull_request:
    description: 'The url of the created PR for review and draft change'
runs:
  using: node20
  main: dist/index.js
